apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ileeiv8qs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ileeiv8qs-python 
  name: ileeiv8qs-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ileeiv8qs-python
    weight: 100 
